"""Add columns

Revision ID: 322d8a82eac0
Revises: 3041d4f29731
Create Date: 2023-04-22 14:47:50.046942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '322d8a82eac0'
down_revision = '3041d4f29731'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('average_ratings', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ratings_count', sa.Integer(), nullable=True))

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.alter_column('permissions',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.alter_column('permissions',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('ratings_count')
        batch_op.drop_column('average_ratings')

    # ### end Alembic commands ###
