"""Remove unnecessary colums

Revision ID: 387c46a9e358
Revises: b94f14e6e298
Create Date: 2023-04-20 23:56:34.177657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '387c46a9e358'
down_revision = 'b94f14e6e298'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('province', sa.String(length=64), nullable=True))
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=64), nullable=True))
        batch_op.drop_column('province')

    # ### end Alembic commands ###
