"""final

Revision ID: 49df1e42d321
Revises: 322d8a82eac0
Create Date: 2023-04-23 01:20:44.289672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49df1e42d321'
down_revision = '322d8a82eac0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('street', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('suburb', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('postal_code', sa.String(length=4), nullable=True))
        batch_op.drop_column('country')
        batch_op.drop_column('state')
        batch_op.drop_column('address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('state', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('country', sa.VARCHAR(length=20), nullable=True))
        batch_op.drop_column('postal_code')
        batch_op.drop_column('suburb')
        batch_op.drop_column('street')

    # ### end Alembic commands ###
