"""Remove province

Revision ID: 74aa68af5cf9
Revises: 387c46a9e358
Create Date: 2023-04-21 01:01:10.459809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74aa68af5cf9'
down_revision = '387c46a9e358'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.drop_column('province')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('province', sa.VARCHAR(length=64), nullable=True))

    # ### end Alembic commands ###
